### PR TITLE
remove display: flex from widget-wrapper fixes #4

### LINKED ISSUE #4: Safari 10.1.1 on macOS 10.12.5
bildschirmfoto 2017-06-06 um 09 13 02

No output in console

### PR DESCRIPTION
**Pull request by mpfeil**
Hopefully fixes #4 and doesn´t break anything

@ubergesundheit could you check it?

### CODE REVIEW

**Comment by ubergesundheit** [comment]
What did you change in the script? Please check in your changes of `src/script.js`

The removal of the `display: flex` at least resolves the tabs aligned to the top on my iphone. The content of the `.widget-list.selected-tab` is still aligned to the top.

I tried to remove the `display: flex` property as well but I am not sure my iphone fetches the updated file.. Maybe you could try this out for me..

**Comment by noerw** [comment]
to fetch the local stylesheet `WIDGET_BASE_URL` has to be replaced with `./` in [this line](https://github.com/sensebox/opensensemap-widget/blob/gh-pages/src/script.js#L567)

**Comment by ubergesundheit** [comment]
I think my approach works as well: change the `WIDGET_BASE_URL` variable to the LAN IP of my computer

**Comment by mpfeil** [comment]
In `src/script.js` I have just changed `WIDGET_BASE_URL` to (in my case) `http://localhost:8000/`

**Comment by ubergesundheit** [comment]
ok, then please remove the built `script.js` from the pull request

**Comment by mpfeil** [comment]
Are you going to build the built `script.js` after merging the PR? Or should I just fix the `WIDGET_BASE_URL`?

And a short screenshot how the widget looks like on safari on my phone:
safari

**Comment by ubergesundheit** [comment]
You can build the `script.js` but only if you include the changes you've made in `src/script.js` and only if it does not break the widget..

It looks exactly like this on my phone. Below the Sensors tab should be `Temperatur` readable.

**Comment by ubergesundheit** [comment]
Yeah, looks better!
But now the drop downs on the pages History and Graph are stretched to the whole width..
image uploaded from ios

**Comment by mpfeil** [comment]
I know. Will check it tomorrow.

**Pull request closed without merging**
